name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --no-scripts --optimize-autoloader

      - name: Log in to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t $DOCKER_USERNAME/laravel-app:latest .
        
      - name: Push Docker image to Docker Hub
        run: docker push $DOCKER_USERNAME/laravel-app:latest
